In [1]:
# Creating random vector of size 15 having only Integers in the range 1-20.
import numpy as np
vector =  np.random.randint(1,20,(15,))

# Reshaping the array to 3 by 5
arr = vector.reshape(3,5)
print(arr.shape)
print(arr)

# Replacing the max in each row by 0
row_max = arr.max(axis=1).reshape(-1,1)
arr = np.where(arr == row_max, 0, arr)
print('\n',arr)


(3, 5)
[[10 18  1  9 10]
 [11 12 19 15  9]
 [ 2 12  4 19  5]]

 [[10  0  1  9 10]
 [11 12  0 15  9]
 [ 2 12  4  0  5]]


In [2]:
# Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements),
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 5, 7]], np.int32)
#shape of the array
print('Shape:', a.shape)
#type of the array
print('Type:', type(a))
#datatype
print('Data type:', a.dtype)

Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [3]:
# Computing the eigenvalues and right eigenvectors
from numpy import linalg as LA
given = np.array([[3, -2], [1, 0]], np.int32)
values, vectors = LA.eig(given)
print('Eigenvalues:', values)
print('\nRight Eigenvectors:\n', vectors)

Eigenvalues: [2. 1.]

Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [4]:
# Computing the sum of the diagonal element
diag = np.array([[0, 1, 2], [3, 4, 5]])
result = np.trace(diag)
print('Sum of diagonal elements:', result)

Sum of diagonal elements: 4


In [5]:
x = np.arange(1,7).reshape(3,2)
x = x.reshape(2,3)
print(x)

[[1 2 3]
 [4 5 6]]
